# Generated by Django 3.2 on 2023-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('geburtsdatum', models.DateField()),
                ('postleitzahl', models.IntegerField()),
                ('ort', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=50)),
                ('handy', models.CharField(max_length=30)),
                ('schaden', models.CharField(max_length=30)),
                ('marke', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('Schadensart', models.CharField(max_length=30)),
                ('kosten', models.FloatField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
